# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dome < Formula
  desc "Dome Platform CLI — AI agent governance"
  homepage "https://domesystems.ai"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dome-systems/releases/releases/download/v0.4.0/dome_0.4.0_darwin_amd64.tar.gz"
      sha256 "34005bbb10c933f5fe0c94283f5444784542f730f2ff1774e176271a1ff0ea67"

      define_method(:install) do
        bin.install "dome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dome-systems/releases/releases/download/v0.4.0/dome_0.4.0_darwin_arm64.tar.gz"
      sha256 "c1148708823eb134c1602a3a15d82a4a2ec9f0b3542b69fb5250956c9484b46f"

      define_method(:install) do
        bin.install "dome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dome-systems/releases/releases/download/v0.4.0/dome_0.4.0_linux_amd64.tar.gz"
      sha256 "d07af0843e698928ff263594c746be9d3e404b79ab014313ed098155ea0191fe"
      define_method(:install) do
        bin.install "dome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dome-systems/releases/releases/download/v0.4.0/dome_0.4.0_linux_arm64.tar.gz"
      sha256 "0deecf83543e867b2083bf6d0b90d638b25c937a2ba34fc1c4b966a5b761893d"
      define_method(:install) do
        bin.install "dome"
      end
    end
  end

  test do
    system "#{bin}/dome", "version"
  end
end
