# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dome < Formula
  desc "Dome Platform CLI — AI agent governance"
  homepage "https://domesystems.ai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dome-systems/releases/releases/download/v0.1.0/dome_0.1.0_darwin_amd64.tar.gz"
      sha256 "cb605d0a72338b994b7a81a10cb6f4c41c14319f2223fce8fb5870860e170a15"

      define_method(:install) do
        bin.install "dome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dome-systems/releases/releases/download/v0.1.0/dome_0.1.0_darwin_arm64.tar.gz"
      sha256 "2b5319b36d1e82b7676ec994219283994d243e903f19167e9308430275058649"

      define_method(:install) do
        bin.install "dome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dome-systems/releases/releases/download/v0.1.0/dome_0.1.0_linux_amd64.tar.gz"
      sha256 "9daf8b28c599ea2ad00adadffdb85938d670bd71d1f49bebd4718147c6b0d6d7"
      define_method(:install) do
        bin.install "dome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dome-systems/releases/releases/download/v0.1.0/dome_0.1.0_linux_arm64.tar.gz"
      sha256 "cb662cb2d9254f8c14487b27261787b35c7fff70afdd221f905f4b8dd269ef09"
      define_method(:install) do
        bin.install "dome"
      end
    end
  end

  test do
    system "#{bin}/dome", "version"
  end
end
