# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dome < Formula
  desc "Dome Platform CLI — AI agent governance"
  homepage "https://domesystems.ai"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dome-systems/releases/releases/download/v0.1.2/dome_0.1.2_darwin_amd64.tar.gz"
      sha256 "f50addde0711ac27eb6d2c6eef09388ffcc3ba2e9c0a2643b93983f079505759"

      define_method(:install) do
        bin.install "dome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dome-systems/releases/releases/download/v0.1.2/dome_0.1.2_darwin_arm64.tar.gz"
      sha256 "954feb65317703492aab6cd09420dae0d6ce9f03cda5f267f92a0dabed0b9c5e"

      define_method(:install) do
        bin.install "dome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dome-systems/releases/releases/download/v0.1.2/dome_0.1.2_linux_amd64.tar.gz"
      sha256 "6d38910136c788f4ec5d9192ef9673477cc550139d1f69b4addb03cd9175bc84"
      define_method(:install) do
        bin.install "dome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dome-systems/releases/releases/download/v0.1.2/dome_0.1.2_linux_arm64.tar.gz"
      sha256 "0938e39bbc6ea184e71518ec9039cb856565f214ba065a22b66778e3f8848e51"
      define_method(:install) do
        bin.install "dome"
      end
    end
  end

  test do
    system "#{bin}/dome", "version"
  end
end
